os: linux
dist: bionic
sudo: required

services:
    - docker

# env:
#     - DOCKER_COMPOSE_VERSION=1.25.3
#     - IMAGE_NAME=minhluc/docker-workspaces
#     - IMAGE_BY_DATE=$IMAGE_NAME:$(date +"%Y%m%d")
before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#     - docker build -t $IMAGE_NAME:latest .
# after_script:
#     - docker push $IMAGE_NAME:latest
#     - docker tag $IMAGE_NAME:latest $IMAGE_BY_DATE
#     - docker push $IMAGE_BY_DATE
script:
    # - docker --rm run $IMAGE_NAME bash -c "echo "done""
    - bash ./build.sh

addons:
    apt:
        packages:
        - docker-ce